
title: ZJ_taotao
subtitle: '生活不止眼前的苟且，还有远方的苟且！！！'
description: ''
keywords:
author: ZJ
language: zh-Hans
timezone: ''

theme: jekyll-theme-merlot

deploy:
  type: git
  repository: https://github.com/SGLGFQ/zj.git
  branch: master